import com.wf.rules.domain.CustomRules;
global com.wf.rules.domain.RulesList rulesList;

dialect "mvel"

rule "Dynamic Amount based rule"
	when
		c : CustomRules(debitAmt > dynamicAmount)
	then
		rulesList.setList("Debit Amount is greater than Threshold: $" + c.getDynamicAmount)
end
rule "Throttle Max Available based rule"
	when
		c : CustomRules(debitAmt > (cap*throttleMaxAvailable))
	then
		rulesList.setList("Debit Amount is greater than "+(c.getThrottleMaxAvailable*100)+"% of Cap")
end