import com.wf.rules.domain.TransactionDetails;
global com.wf.rules.domain.TransactionStatus transactionStatus;

dialect "mvel"

rule "Counterparty name based rule"
	when
		TransactionDetails(nm=="CITI")
	then
		transactionStatus.addOnHoldReason("Transaction for CITI are kept on hold")
end
rule "Payment Rail based rule"
	when
		TransactionDetails(pmtRail=="RTL")
	then
		transactionStatus.addOnHoldReason("All retail transactions kept on hold")
end